---
include:
  - '**/*.rb'
exclude:
  - '**/spec/**/*'
  - qa/qa/specs/features/**/*
  - vendor/**/*
  - '.bundle/**/*'
require:
  - actioncable
  - actionmailer
  - actionpack
  - actionview
  - activejob
  - activemodel
  - activerecord
  - activestorage
  - activesupport
domains: []
reporters:
  - rubocop # diagnostics
  - require_not_found
formatter:
  rubocop: # formatting
require_paths: []
plugins: []
max_files: 20000
